### ISSUE TITLE
Only auto-scroll log window if already at bottom

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp-simulator#6]
System log should not auto-scroll to bottom when new message are received, unless it's already at the bottom.

The current behaviour means it's very hard to look at earlier messages, since every new messages causes the window to auto-scroll.

**Comment by tomasrook** [comment]
Ok, good point.
I have updated the behaviour to auto scroll to the last item only if no item is selected or the last item is selected. If you select some other item in the list, it will remain selected and the list is filled without scrolling. Seemed to be the logical solution since there is not much place to add a 'Always show last row' checkbox.
Is fixed in release 1.0.1.4 B4

**Comment by emiltin** [comment]
Great
